import { cn } from '@/libs/utils/cn'
import { Montserrat } from 'next/font/google'
import './globals.css'

/** components */
import { Header } from '@/components/layout/header'
import { Footer } from '@/components/layout/footer'
import { Preloader } from '@/components/layout/preloader'
import { ThemeSetter } from '@/components/layout/theme-setter'

import type { Metadata } from 'next'

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('typo-body-1 flex min-h-screen flex-col', montserrat.className)}>
        <Preloader />
        <Header />
        <main className="flex-1">{children}</main>
        <Footer />
        <ThemeSetter />
      </body>
    </html>
  )
}
